### ISSUE TITLE
Bad initial state when Preview Sim occurs in the middle of an interaction

### ISSUE THREAD

**Issue by phet-steele** [phetsims/molecule-polarity#105]
Follow: https://phet-dev.colorado.edu/html/molecule-polarity/1.1.0-rc.1/phet-io/wrappers/studio/

1. Enter a screen, and turn on the Electric Field
2. Start dragging the molecule such that **if** you released your mouse it would rotate to align itself, but don't release.
3. Move your mouse out of the iframe while still holding your mouse down (this is not the bug), then click "Preview Sim"

In the sim, note two things that are not saved:

- Cue arrows around the atoms do not stay hidden. They shouldn't be back.
- The molecule does not react to the presence of the Electric Field (doesn't rotate to align itself) until you click on the molecule or alter an atom's electronegativity.

Seen on Win 10 Chrome. For phetsims/QA/issues/627.

**Comment by pixelzoom** [comment]
> 3. Move your mouse out of the iframe while still holding your mouse down (this is not the bug), then click "Preview Sim"

The fact that this doesn't interrupt the interaction that's in progress feels really buggy to me.  How can we possibily put the sim in the correct starting state when the Preview button is pressed in the middle of a drag cycle?

@zepumph @samreid thoughts?

**Comment by pixelzoom** [comment]
> * Cue arrows around the atoms do not stay hidden. They shouldn't be back.

I was asked not to instrument the hint arrows, so their state is not saved and restored.  If it's important to save/restore their state, they will need to be instrumented.  @arouinfar how would you like to proceed with this?

**Comment by pixelzoom** [comment]
> If it's important to save/restore their state, they will need to be instrumented.

Actually, we probably shouldn't instrument the individual hint arrows.  It's more involved than that. I'll need to create a read-only Property that keeps track of whether the hint arrows are visible, and instrument that Property.

**Comment by pixelzoom** [comment]
Btw... These are really 2 separate problems.  Hint arrows is an issue no matter how you use the sim:

1. Start the sim in Studio
2. Go to Two Atoms screen
3. Move the molecule, so that the hint arrows go away
4. Press Preview in Studio.  Note that the hint arrows appear in the preview sim.

So... I'm going to split this into 2 issues, and edit some comments.

**Comment by pixelzoom** [comment]
Here's the reason why the molecule doesn't align with the E-field in the Preview sim.  In MPModel.js:

```js
  step( dt ) {

    // If the E-field is on and the user isn't controlling the molecule's orientation, animate molecule rotation.
    if ( this.eFieldEnabledProperty.value && !this.molecule.isDraggingProperty.value ) {
      this.updateMoleculeOrientation( this.molecule );
    }
  }
```

The molecules orientation is not updated while it's being dragged.  `molecule.isDraggingProperty` is an instrumented Property, so it's state is being save and restore.  Since you press "Preview Sim" while you were in the middle of a drag, the Previewed sim thinks it's in the middle of a drag (because it is!) and doesn't update the molecule orientation. 

I'm familiar with lots of sims that have something like `isDraggingProperty`, often called something like `isUserControlledProperty`.  I would expect that those sims would have a similar problem if we allow Studio buttons to be pressed in the middle of sim interactions.

**Comment by zepumph** [comment]
>The fact that leaving the iframe doesn't interrupt the interaction that's in progress feels buggy to me

There isn't really an event to listen to at this time for this. @jonathanolson is there a reason why we don't interrupt listeners when a Pointer is removed from a display?

>The molecule's orientation is not updated while it's being dragged. molecule.isDraggingProperty is an instrumented Property, so it's state is being saved and restored. Since you pressed "Preview Sim" while you were in the middle of a drag, the Preview sim thinks it's in the middle of a drag (because it is!) and doesn't update the molecule orientation.

I would consider `isDraggingProperty` a transient value, and not something that should be stateful. I would start in this issue by setting that to be `phetioState:false`  and seeing how that feels.

**Comment by pixelzoom** [comment]
All kind of other bad behavior as the result of not interrupting when the pointer leaves the iframe. 

Examples using Studio in "Two Atoms" screen:

1. Press on the molecule and start dragging
2. Move pointer outside of sim iframe and release pointer
3. Move pointer back inside of sim iframe.  The pointer is no longer down, but the molecule still rotates as the pointer move. You have to press and release to make it stop.

1. Pointer down on the E-field on/off button
2. Move pointer outside of sim iframe and release pointer
3. Move the pointer back inside the sim iframe. The cursor changes to 'pointer', and moving the pointer left/right toggle the on/off switch.

1. Pointer down on one of the Electronegativity sliders
2. Move pointer outside of sim iframe and release pointer
3. Move the pointer back inside the sim iframe. The cursor changes to 'pointer', and moving the pointer continues to interact with the slider.

**Comment by pixelzoom** [comment]
More badness, very sim-specific in this case:

When an Electronegativity (EN) slider is dragging, the value is continuous. When the slider is released, it snaps to 0.2 intervals. Using these steps, the Preview Sim starts up in a state where the slider is not dragging, and the value is not a 0.2 interval:

1. Start sim in Studio, go to Two Atoms screen
2. Start dragging one of the EN sliders.
3. With the EN slider thumb between 2 of the tick marks, move the pointer outside of the sim iframe.
4. Press the Preview Sim button.  The Preview sim is initialized with an EN value that is not a 0.2 interval.

**Comment by pixelzoom** [comment]
If I'm not running the sim in an iframe, interaction appears to be interrupted when the pointer leaves the bounds of the browser.  I think this is the behavior that we want when the point leaves an iframe.

**Comment by pixelzoom** [comment]
`molecule.isDraggingProperty` has been set to `phetioState: false` in master and 1.1 branches.  See above commits.

**Comment by pixelzoom** [comment]
Reducing the priority of this, because the research collaborator for #87 is unlikely to be customizing using Studio.  

This seems like a general PhET-iO issue, that should be moved to a general repo.  Suggestions on which repo?

**Comment by samreid** [comment]
Since we encourage embedding PhET simulations in iframes without using PhET-iO, maybe this issue is not specific to PhET-iO?  For instance, the behavior appears in build/phet/molecule-polarity_en_iframe_phet.html as well, which is produced on build and does not use any PhET-iO.  But I agree PhET-iO leverages iframes heavily.  Chipper defines the sim-iframe template.  But this problem also feels a little like it belongs in Joist.  What do you recommend?

**Comment by pixelzoom** [comment]
My recommendation is in https://github.com/phetsims/molecule-polarity/issues/105#issuecomment-804471507:
> If I'm not running the sim in an iframe, interaction appears to be interrupted when the pointer leaves the bounds of the browser. I think this is the behavior that we want when the pointer leaves an iframe.

**Comment by jonathanolson** [comment]
I'm looking more in depth into this, but friction (the dragging of the book) and molecule shapes (the rotation of the molecule) are both cases where it would be incredibly annoying if the action got interrupted when the pointer went out of the window/iframe. Similarly for any case where you're trying to drag something near the border (CCK?)

**Comment by jonathanolson** [comment]
Most of the items in https://github.com/phetsims/molecule-polarity/issues/105#issuecomment-804460900 seem like actual bugs with how Scenery is handling things, rather than general problems that would result from allowing input from pointers that have gone outside of the iframe.

We SHOULD get events in those cases, the drag releases should happen, and things shouldn't break. @pixelzoom what browser were you using, so I could investigate?

**Comment by pixelzoom** [comment]
Sim-specific issues have been moved to new issues #106 and #107.
The general issue of when to interrupt input has been moved to  https://github.com/phetsims/scenery/issues/1186, please continue discussion there.

Closing.
