### ISSUE TITLE
Rotating hint arrows behave differently than in published

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-polarity#113]
For https://github.com/phetsims/QA/issues/631. Found while confirming https://github.com/phetsims/molecule-polarity/issues/107. Also seems to happen in rc.1, so unrelated to any fixes done before rc.2. This issue seems very minor and may not be worth addressing.

When hint arrows are on and the electric field is turned on, while on the second screen, the arrows remain when while the molecule rotates. How the arrows behave during this is different between the published sim and the rc.

Published:
![published](https://user-images.githubusercontent.com/41024075/112889936-82900180-9093-11eb-91b9-f2f70d17f922.gif)
RC:
![vsnow](https://user-images.githubusercontent.com/41024075/112889980-8f145a00-9093-11eb-94e1-29a64ce2bd1a.gif)

**Comment by pixelzoom** [comment]
This is behaving as expected.  The requirement for the hint arrows is that they disappear when the user performs a drag action on any part of the molecule.   That has not occurred in the scenario that is described, so the hint arrows remain.  

Assigning to @arouinfar to decide if the requirements should be changed.  If so, please specify the additional things that should cause the hint arrows to disappear.  Also note that this has become a tricky, complicted feature due to PhET-iO. So any changes to this feature will not be inexpensive.

**Comment by KatieWoe** [comment]
The issue I'm pointing out isn't that the arrows stay, it's how they are positioned when the molecule moves. As shown in the gif, this behavior is different than the published version.

**Comment by pixelzoom** [comment]
I'm having a really difficult time parsing this sentence:
> When hint arrows are on and the electric field is turned on, while on the second screen, the arrows remain when while the molecule rotates

So let me see if I understand... You're reporting that the green hint arrows no longer rotate with the molecule. Do I underarand that correctly?

**Comment by KatieWoe** [comment]
Yes.

**Comment by pixelzoom** [comment]
OK thanks.

This definitely does not need to be addressed for #87 (research study).  I'll self-assign and consider addressing it later for a general release.

**Comment by arouinfar** [comment]
> This definitely does not need to be addressed for #87 (research study). I'll self-assign and consider addressing it later for a general release.

Agreed that it is not important for #87 @pixelzoom.

It looks like the green hint arrows will rotate with the molecule while the molecule is in motion, but once it stops, the arrows pop back to the left/right side of atom B instead of staying at the top/bottom. I'd consider this a minor issue. It looks a bit strange but I don't think it will impact usability. Looks like the change crept in somewhere between [1.1.0-dev.3](https://phet-dev.colorado.edu/html/molecule-polarity/1.1.0-dev.3/phet/molecule-polarity_en_phet.html?screens=2) and [1.1.0-rc.1](https://phet-dev.colorado.edu/html/molecule-polarity/1.1.0-rc.1/phet/molecule-polarity_en_phet.html?screens=2).

@pixelzoom I think it'd be worth looking into for the next release, but I'm totally fine with closing this as wont-fix if it requires anything complicated.

**Comment by pixelzoom** [comment]
In In #112, we decided that the next production release will be based on a new branch. So this issue does not need to be addressed in the 1.1 branch, it is sufficient to address it in master.

**Comment by pixelzoom** [comment]
By bisecting, I determined that this regression was introduced in 2a0f176133c3864763775dc14ca97175c8046ce2 on 3/8/21. The commit comment is "fix rotation arrows when dipole angle is zero".

**Comment by pixelzoom** [comment]
Reverting 2a0f176 will fix the problem, and it seems that other changes (probably the normalization of angle) have resolved #95.  So I could do that. 

But there are other weird things that result from trying to keep the orientation of the rotation hint arrows aligned with the molecular dipole.  For example in [1.1.0-rc.1](https://phet-dev.colorado.edu/html/molecule-polarity/1.1.0-rc.1/phet/molecule-polarity_en_phet.html?screens=2):

1. Set EN of Atom B to "less"
2. Change EN of Atom C to something other than "less", then change it back to "less".  You'll see the rotation arrows jump between 2 orientations as the molecular dipole changes.

Since these are hint arrows, I don't see any reason to make them rotate to match the molecular dipole orientation.  It would be much less distracting if they remained in their original orientation, and never moved.  @arouinfar is that OK with you?

**Comment by pixelzoom** [comment]
@arouinfar I went ahead and made the change that I described in the previous comment.  The rotation arrows now remain in a fixed orientation, they do not align with the molecular dipole.  The complexity involved, and the number of problems that have been encountered, just don't seem worth the bother for hint arrows. 

Compare:

[1.2.0-dev.1](https://phet-dev.colorado.edu/html/molecule-polarity/1.2.0-dev.1/phet/molecule-polarity_en_phet.html) has the old behavior.

[1.2.0-dev.2](https://phet-dev.colorado.edu/html/molecule-polarity/1.2.0-dev.2/phet/molecule-polarity_en_phet.html) has the new behavior.

If this is satisfactory, please close.  If not, assign back to me for continued work.

**Comment by pixelzoom** [comment]
4/15/21 design meeting @arouinfar @kathy-phet 

Looks good, closing.

**Comment by KatieWoe** [comment]
Noting that this behavior is seen in https://github.com/phetsims/qa/issues/688

**Comment by pixelzoom** [comment]
@KatieWoe please clarify -- which behavior?  The original problem that you reported, or the new behavior that the design team signed off on?

**Comment by pixelzoom** [comment]
To be on the safe side, I'm going to reopen this and assign to @KatieWoe.  If there's a problem related to phetsims/qa#688 please elaborate.  If there's no problem, re-close this issue.

**Comment by pixelzoom** [comment]
The approved change is described in https://github.com/phetsims/molecule-polarity/issues/113#issuecomment-812874247:
> Since these are hint arrows, I don't see any reason to make them rotate to match the molecular dipole orientation. It would be much less distracting if they remained in their original orientation, and never moved. 

So it sounds like this is what you're seeing, and the sim is behaving as desired. But @KatieWoe please confirm, and close if OK.

**Comment by KatieWoe** [comment]
Ok
