### ISSUE TITLE
"Real Molecules is not currently available in HTML5" ?

### ISSUE THREAD

**Issue by DevonQui** [phetsims/molecule-polarity#119]
**Test device**
MacBook Pro
**Operating System**
11.5
**Browser**
Safari
**Problem description**
This is for https://github.com/phetsims/qa/issues/680

The "Real Molecules" screen doesn't have a simulation attached to it, only a redirect link to a Java based version of the sim. I'm not sure if this was intentional so feel free to close, I just haven't run into this before.

**Steps to reproduce**
1. Open sim
2. Click onto Real Molecules screen and notice the message "Real Molecules is not currently available in HTML5"

**Visuals**
<img width="697" alt="Screen Shot 2021-07-27 at 10 54 26 AM" src="https://user-images.githubusercontent.com/72042459/127196484-d8b6073b-892f-40f8-a844-4e0298db2268.png">

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Molecule Polarity‬
URL: https://phet-dev.colorado.edu/html/molecule-polarity/1.2.0-dev.3/phet/molecule-polarity_all_phet.html
Version: 1.2.0-dev.3 2021-07-26 23:04:53 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15
Language: en-us
Window: 1440x792
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by pixelzoom** [comment]
Thanks for reporting @DevonQui.  

It is indeed unusual to publish a sim with an incomplete screen. But this was requested by @kathy-phet in https://github.com/phetsims/molecule-polarity/issues/27#issuecomment-311999438.  Since this screen is popular among teachers, we thought it best to provide information on how they could still get to it in the Java version. 

So nothing to do there, and closing this issue.
