### ISSUE TITLE
Molecular dipole arrow continues off-screen

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/molecule-polarity#129]
For https://github.com/phetsims/qa/issues/688

When atoms A and C are close to one another and have a large electronegativity difference with atom B, the molecular dipole arrow is so large it is off the screen. 
<img width="1132" alt="Screen Shot 2021-08-06 at 10 24 56 AM" src="https://user-images.githubusercontent.com/87318828/128525739-627e7182-a180-4517-bd0d-052a60c5b3f3.png">

<img width="1132" alt="Screen Shot 2021-08-06 at 10 38 54 AM" src="https://user-images.githubusercontent.com/87318828/128527393-e048d5b2-ce9f-4792-9c90-ee75bc1635a7.png">

**Comment by pixelzoom** [comment]
The only way to prevent this would be to change the range of electronegativity. And that might have negative impact (sorry, couldn't resist :) on other aspects of the sim.  I also don't think there's a problem with it being so large that it's off-screen.  This sim is qualitative, not quantitative, and it tells the student that the diploe is really large.  So I think this behavior is fine, and I recommend no change. 

@arouinfar your call.

**Comment by Nancy-Salpepi** [comment]
My other thought on this is why do we let the A and C atoms get that close?

**Comment by pixelzoom** [comment]
Because it would cause both pedagocial and UX problems.

Pedagogical:  It's phyically accurate to let them get that close. Constraining them otherwise could lead to misconceptions, like there's some force keeping A and C apart. And it would certainly make it impossible to discover some things: For example, you couldn't discover that the molecule dipole is at its maximum when A and C are at the same position.

UX: If A and C can't get close, then you can't rotate A past C, and visa versa.

On devices that allow it, you can resize the browser window to see the full dipole. Here's a screenshot with `?dev` that shows the layoutBounds:

<img width="988" alt="screenshot_1133" src="https://user-images.githubusercontent.com/3046552/128552602-01b210c0-785f-4ea8-902b-410ce9fe5a10.png">

On devices that don't allow resizing the browser window, you can rotate the molecule to see the full diploe. Screenshot:

<img width="989" alt="screenshot_1134" src="https://user-images.githubusercontent.com/3046552/128552650-ddc5e0b3-87ae-4785-81d8-0b2f0318af7e.png">

**Comment by Nancy-Salpepi** [comment]
Thanks for taking the time to respond. Much appreciated.

**Comment by Nancy-Salpepi** [comment]
I actually just found this in teacher tips. I think from now on I am going to read them (if available) before working on a sim. 
• The Three Atoms screen allows for students to change the bond angle between the outer atoms
(A & C). The AB and BC bonds are treated independently, and the model does not allow for these
atoms to repel each other. To explore how atoms would repel one another when the bond angles
are changed, see the Molecule Shapes simulation. The AB and BC bonds are treated
independently.

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi. We generally try to avoid items going off-screen, so it's a good thing to generally look for. That said, there are always exceptions. We sometimes allow things to extend off-screen if it's an extreme value or if repositioning the object can address the issue. In this case, both are true. There isn't anything to do here, so I'll go ahead and close.
