### ISSUE TITLE
Z-ordering of atoms should be stateful

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-polarity#157]
**Device**
Samsung
**OS**
Win 11
**Browser**
Firefox
**Problem Description**
For https://github.com/phetsims/qa/issues/952.
The z-ordering of the A and C atoms on the second screen are not stateful. We should be using IndexedNodeIO.
**Visuals**
![layerstateful](https://github.com/phetsims/molecule-polarity/assets/41024075/f0399a78-9d6d-40c5-b1ea-87e2306cbda1)

**Comment by pixelzoom** [comment]
Reproduced in master and 1.3.0-dev.3.  

In the above commits, I made the rendering order stateful for atoms A and C.  By passing these options to the 2 AtomNode instances in TriatomicMoleculeNode.ts:

```ts
      // Make z-ordering stateful, see https://github.com/phetsims/molecule-polarity/issues/157
      phetioType: IndexedNodeIO,
      phetioState: true
```

This is relevant only to atoms A and C in the "Three Atoms" screen, because those atoms have a BondAngleDragListener, which changes the rendering order via a call to `moveToFront`. 

Tested in State Wrapper and Studio.  This required and API change, but no changes to migration rules. 

@KatieWoe please verify in master, close if OK.

**Comment by KatieWoe** [comment]
Looks good on master
