### ISSUE TITLE
Colors Keys disappear when migrating 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/molecule-polarity#162]
**Test device**
MacBook Air M1 chip

**Operating System**
13.4

**Browser**
Safari 16.5

**Problem description**
For https://github.com/phetsims/qa/issues/956, on the Two Atoms screen, the colorKeys disappear when I migrate from 1.2 to 1.3.

**Steps to reproduce**
1. On the Two Atoms Screen, select the Electrostatic Potential radio button
2. Press Migrate Now --> the moleculePolarity.twoAtomsScreen.view.colorKeys.electrostaticPotentialColorKey.visibleProperty is false

If you initially select the Electron Density radio button and then press migrate now, the moleculePolarity.twoAtomsScreen.view.colorKeys.electronDensityColorKey.visibleProperty will be false in 1.3.

Switching back and forth between radio buttons fixes the problem. 
 
**Visuals**

https://github.com/phetsims/molecule-polarity/assets/87318828/4a7bc4ed-6bb0-453f-9d23-7b807615869f

**Comment by KatieWoe** [comment]
Some additional oddities I saw:
1. On the bottom screen, turn on Electrostatic Potential
2. On the top screen have Electrostatic Potential off
3. Migrate
4. Observe that the bar is still there in the bottom screen

![wonk](https://github.com/phetsims/molecule-polarity/assets/41024075/c7741608-870c-42f0-8590-61254e6e4035)

**Comment by pixelzoom** [comment]
In the above commit, I addressed this problems reported by @Nancy-Salpepi and @KatieWoe  in master and 1.3 branches.

I realized that by removing `colorKeyNode.visibleProperty`, we had lost the ability to hide the color key independently of the "Surface" radio button selection.  And that's a PhET-iO feature that had been previously requested.  So I restored the tandem structure so that 1.2 and 1.3 are identical, i.e.:

<img width="178" alt="screenshot_2638" src="https://github.com/phetsims/molecule-polarity/assets/3046552/7839a711-fd25-413d-8355-f87d291a4cc5">

This also required changing the API file, and deleting a migration rule.

@Nancy-Salpepi or @KatieWoe please test in master. If it looks OK, please change the label to "fixed-awaiting-deploy", and we'll verify the 1.3 branch in the next RC.

**Comment by Nancy-Salpepi** [comment]
The structures are identical in Studio 1.2 and 1.3. 
I wasn't able to test migration in master because the migration wrapper was trying to compare 1.3 and 1.4.

**Comment by pixelzoom** [comment]
To test migration in master during RC testing, you will (in general) need to add the `oldVersion` query parameter -- in this case `oldVersion=1.2`.  When `oldVersion` is not provided, the Migration wrapper uses the previous version, so that's why master (which is now on 1.4) is looking for 1.3 (which has not yet been published).   This should be described in the documentation for the Migration wrapper, and/or in whatever QA is using for migration testing instructions.  Mentioning @zepumph and @samreid in case they are not aware of this.

**Comment by pixelzoom** [comment]
@Nancy-Salpepi said:
> I wasn't able to test migration in master because the migration wrapper was trying to compare 1.3 and 1.4.

See https://github.com/phetsims/phet-io-wrappers/issues/525

**Comment by Nancy-Salpepi** [comment]
Thanks for letting me know about the query parameter. I will take a look at the migration wrapper now and change status if needed.

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.2.
