### ISSUE TITLE
LinkedElements don't appear in Featured tree

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-polarity#163]
For https://github.com/phetsims/qa/issues/956.
See https://github.com/phetsims/studio/issues/309.

**Comment by zepumph** [comment]
From https://github.com/phetsims/studio/issues/309, I need to cherry pick https://github.com/phetsims/sun/commit/08180ca3e5118d72953fdf9602ce8e4fd577c481 but nothing else, since there is no audio toggle button, or scenery-phet components listed in https://github.com/phetsims/scenery-phet/commit/75501d1c6eb0503846b9201cd4e377c9ebf4aa13.

I'll make that happen now on MP 1.3 release branch.

**Comment by zepumph** [comment]
Cherry picked and confirmed in local build. Ready to pass onto QA in next rc.

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.2 (followed instructions above).
