### ISSUE TITLE
Can cursor image match Java "rotate cursor" when mousing over atom? 

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/molecule-polarity#35]
In Java, we added a cursor rotation mouse image, to help students realize that they can rotate the atom. 

Can we do this again in HTML5? I don't see it in the current implementation.

**Comment by pixelzoom** [comment]
The cursor in Java was a custom cursor.  We currently don't have support for custom cursors in HTML5, and there is no built-in cursor that looks like the one in Java.

We realized this early in the port of Molecule Polarity to HTML5, and switched to an indicator that appears around the rotatable molecule.  It appears in the "Three Atoms" screen, see the green arrows around atom 'B':

![screenshot_302](https://user-images.githubusercontent.com/3046552/28041972-9df3106e-6588-11e7-84ca-67f0c2161817.png)

These arrows appear on mouse over, and they disappear when you start interacting with atom B.

In the "Two Atoms" screen, my recollection is that we decided not to use these arrows, since (a) we're not rotating the atoms, and (b) it's obvious what happens as soon as you move an atom.

@kathy-phet Is that satisfactory, or do you still want a change?

**Comment by pixelzoom** [comment]
We also thought that the green "rotate" arrows around atom B were more consistent with the "translate" arrows that appear around atoms A and C.  Now all 3 atoms have an indicator that disappears when you start interacting, and the cursor is the same.

**Comment by pixelzoom** [comment]
FYI, you can view the built-in cursors at http://phetsims.github.io/scenery/examples/cursors.html.  Mouse over the rectangles to change your cursor.  Some of these are not supported by all browsers.

**Comment by pixelzoom** [comment]
In the code for the green "rotate" arrows around atom B, I see this comment that describes the arrows:

> A pair of arrows that are placed around an atom, indicating that dragging the atom will change the molecule angle.

Since the arrows are used to indicate that dragging the atom will change the molecule angle, I think it would be fine to use these arrows around atoms A and B in the "Two Atoms" screen.  If that's something you'd like @kathy-phet ...

**Comment by kathy-phet** [comment]
@pixelzoom @emily-phet -- I think I would favor using the arrows that are currently used for atoms A and C on screen 2 on the A/B atoms of screen 1.   I could live with the way it is now, but I think the consistency of making that functionality explicit between the two screens is good, and it is more likely that they will see some behavior when they turn on the electric field if they have tried rotating the atom at some point. Otherwise, with the default positioning of the current A-B atom and electronegativity configuration nothing happens when you turn on the electric field.

**Comment by pixelzoom** [comment]
@kathy-phet said:
>  ... I think I would favor using the arrows that are currently used for atoms A and C on screen 2 on the A/B atoms of screen 1. ...

Those arrows are documented as:
> A pair of arrows that are placed around an atom, indicating that dragging the atom will change the bond angle.

... and we're not changing bond angle in the "Two Atoms" screen, we're rotating the molecule.  There's nothing technical preventing their use in "Two Atoms", but that was not their original purpose when designed, as indicated by the documentation. And I'm wondering why we'd want to change this, since Java used the "rotate molecule" indicator in "Two Atoms", and that seemed to work just fine.

@emily-phet How do you want to proceed?

**Comment by kathy-phet** [comment]
Well, in the three molecule screen the rotation arrows make sense because it spins around that central atom. In the two molecule screen it translates the atoms about the central point of rotation. So the behavior in the two atom screen seems more consistent with the look of the A/C atoms.

**Comment by pixelzoom** [comment]
OK, I will change the behavior from the Java sim.

**Comment by pixelzoom** [comment]
... and change the documentation to match the new re-purposing of the "bond angle" arrows.

**Comment by kathy-phet** [comment]
Let's let @emily-phet weigh in too.

**Comment by pixelzoom** [comment]
It was trivial to add the arrows, 4 lines of code. So here are two dev versions that let you compare the two different types of arrows on the A and B atoms in "Two Atoms" screen.  Mouse over the atoms to see the arrows.  Compare with the "Three Atoms" screen.

[1.0.0-dev.13](http://www.colorado.edu/physics/phet/dev/html/molecule-polarity/1.0.0-dev.13/molecule-polarity_en.html) - bond angle (straight) arrows

[1.0.0-dev.14](http://www.colorado.edu/physics/phet/dev/html/molecule-polarity/1.0.0-dev.14/molecule-polarity_en.html) - rotation (curvy) arrows, matches the [Java version](https://phet.colorado.edu/en/simulation/molecule-polarity)

**Comment by pixelzoom** [comment]
Note to self: It we go with 1.0.0-dev.13 (bond angle arrows), then amend the documentation for BondAngleArrowsNode to indicate that they have been repurposed.  Something like:

```js
 * NOTE: These arrows were repurposed to indicate molecule rotation in the 'Two Atoms' screen.
 * See https://github.com/phetsims/molecule-polarity/issues/35.
```

**Comment by emily-phet** [comment]
To be honest, I don't see a difference between the two versions... we're talking about the two curved arrows that indicate rotation that appear over individual atoms to indicate rotation?

**Comment by pixelzoom** [comment]
@emily-phet said:
>  I don't see a difference between the two versions.

"Two Atoms" screen, mouse over the A atom, arrows will appear around the atom

In 1.0.0-dev-13, the arrows look like this:

![screenshot_56](https://user-images.githubusercontent.com/3046552/28102298-8f7302a2-668b-11e7-8aa3-523c20967911.png)

In 1.0.0-dev.14, the arrows look like this:

![screenshot_55](https://user-images.githubusercontent.com/3046552/28102307-975d90a4-668b-11e7-8873-57fdea08bb94.png)

**Comment by pixelzoom** [comment]
7/13/17 design meeting:
• use 1.0.0-dev-13 (straight arrows)
• change documentation and type names to indicate new behavior ("move molecule")

**Comment by pixelzoom** [comment]
Changes have been completed, and internal documentation has been changed.

@kathy-phet or @emily-phet please verify in this dev version:
http://www.colorado.edu/physics/phet/dev/html/molecule-polarity/1.0.0-dev.19/molecule-polarity_en.html

Feel free to close if it looks OK.

**Comment by pixelzoom** [comment]
Behavior of arrows was approved in https://github.com/phetsims/molecule-polarity/issues/50#issuecomment-315484194, so closing this issue.
