### ISSUE TITLE
Suggestion Re: Background color choice for Real Molecules placeholder screen 

### ISSUE THREAD

**Issue by emily-phet** [phetsims/molecule-polarity#36]
Should the background color on the Real Molecules placeholder screen be the same as the background color for the first two screen? 
Perhaps it is technically the same color, but slightly 'grayed' out like other dialogs in PhET...but since there's no screen to go back to maybe it should stay the exact same background color.

I don't have a strong feeling about this:
- if this was already discussed go ahead with whatever was decided...
- if there is a technical reason having to do with dialog boxes and how the background color is altered, I would not consider this worth extra effort to generalize a solution, so leave as is.

**Comment by pixelzoom** [comment]
The background color is the same for all 3 screens.  "Real Molecules is not available in HTML5" is in a modal dialog.  Modal means that you can't interact with anything on the screen while the dialog is open.  The default behavior of a modal dialog is to therefore dim everything behind it while the dialog is open.   The About dialog (available via the PhET menu) is another example of a modal dialog. 

I can certainly change the default behavior so that it doesn't dim everything behind it.

Let me know how you'd like to proceed.

**Comment by ariel-phet** [comment]
Let's leave the current behavior considering @pixelzoom comments (I think this makes the dialog consistent with other such uses). Closing.
