### ISSUE TITLE
Is overlapping a problem with Molecule "add-ons"?

### ISSUE THREAD

**Issue by zepumph** [phetsims/molecule-polarity#68]
from code review #30 
Do we want to support a bit nicer display when pieces of the molecules intersect on the triatomic screen?

The problem is illustrated below.

![image](https://user-images.githubusercontent.com/6856943/28388741-29041c7c-6c80-11e7-87ac-9e44921503fe.png)

**Comment by pixelzoom** [comment]
Long long ago, we decided not to flip which side of the bond the dipole appears on, because having the dipole switching sides while dragging was distracting.  So we decided to live with "overlap" situations like the one shown above.  @emily-phet are you OK with that original decision, or do you want to revisit?

If we want to revisit...  The decision not to "switch sides" informed the Java implementation, and was ported to the HTML5.  Positioning of the bond dipoles is handled by the bond, which knows nothing about other bonds.  The dipole is positioned parallel to the bond, and always on the same "side" of the bond.  If we want to position the dipoles in a way that minimizes overlap that is (a) a non-trivial problem and (b) a totally different implementation of the view for bonds, triatomic molecule, _and_ diatomic molecule (since it shares the same bond implementation).  The bond would no longer be responsible for positioning the dipole.  The molecule would need to be responsible for repositioning the dipole, so it could account for the position of all dipoles and partial charges. This would be a rewrite, not a change.

@emily-phet let me know how you want to proceed.

**Comment by pixelzoom** [comment]
In case there's any question... Here's the same scenario, with the same overlap, in the Java version:

![screenshot_327](https://user-images.githubusercontent.com/3046552/28392290-849befec-6c9e-11e7-9622-e9f79ef7d8ff.png)

**Comment by emily-phet** [comment]
@pixelzoom We should leave this as-is, allowing bond dipoles to overlap.
